In [1]:
%matplotlib inline
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


from sklearn.model_selection import cross_val_score, train_test_split
from sklearn import tree
from sklearn import metrics

In [2]:
#data = pd.read_csv(os.path.join("data", "loan_sub.csv"), sep=',')
data = pd.read_csv(os.path.join("../input", "loan_sub.csv"), sep=',')

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (19,47) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title',
       'emp_length', 'home_ownership', 'annual_inc', 'is_inc_v', 'issue_d',
       'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose', 'title',
       'zip_code', 'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'mths_since_last_delinq', 'mths_since_last_record',
       'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'mths_since_last_major_derog',
       'policy_code', 'not_compliant', 'status', 'inactive_loans', 'bad_loans',
       'emp_length_num', 'grade_num', 'sub_grade_num', 'delinq_2yrs_zero',
       'pub_rec_zero', 'collections_12_mths_zero', 'short_emp',
       'payment_inc_ratio', 'final_d', 'last_delinq_none', 'last_record_none',
       'last_major_derog_none'],
      dtype='object')

In [4]:
# safe_loans =  1 => safe
# safe_loans = -1 => risky
data['safe_loans'] = data['bad_loans'].apply(lambda x : +1 if x==0 else -1)
data = data.drop('bad_loans', axis=1)

In [5]:
data['safe_loans'].value_counts(normalize=True)

 1    0.811185
-1    0.188815
Name: safe_loans, dtype: float64

In [6]:
cols = ['grade', 'term','home_ownership', 'emp_length']
target = 'safe_loans'

data = data[cols + [target]]
data.head()

  grade        term home_ownership emp_length  safe_loans
0     B   36 months           RENT  10+ years           1
1     C   60 months           RENT   < 1 year          -1
2     C   36 months           RENT  10+ years           1
3     C   36 months           RENT  10+ years           1
4     A   36 months           RENT    3 years           1

In [7]:
data['safe_loans'].value_counts()

 1    99457
-1    23150
Name: safe_loans, dtype: int64

In [8]:

# use the percentage of bad and good loans to undersample the safe loans.
bad_ones = data[data[target] == -1]
safe_ones = data[data[target] == 1]
percentage = len(bad_ones)/float(len(safe_ones))

risky_loans = bad_ones
safe_loans = safe_ones.sample(frac=percentage, random_state=33)

# combine two kinds of loans
data_set = pd.concat([risky_loans, safe_loans], axis=0)
data_set

       grade        term home_ownership emp_length  safe_loans
1          C   60 months           RENT   < 1 year          -1
6          F   60 months            OWN    4 years          -1
7          B   60 months           RENT   < 1 year          -1
10         C   36 months           RENT   < 1 year          -1
12         B   36 months           RENT    3 years          -1
18         B   36 months           RENT  10+ years          -1
21         B   36 months           RENT     1 year          -1
23         C   36 months           RENT    9 years          -1
24         D   60 months           RENT    2 years          -1
41         A   36 months       MORTGAGE  10+ years          -1
45         B   36 months       MORTGAGE    8 years          -1
48         C   36 months           RENT    4 years          -1
50         E   60 months           RENT    7 years          -1
58         D   60 months           RENT    5 years          -1
60         F   60 months           RENT    4 years          -1
63         D   36 months           RENT    5 years          -1
87         D   60 months       MORTGAGE    7 years          -1
89         B   36 months           RENT    2 years          -1
93         D   60 months           RENT  10+ years          -1
102        D   36 months           RENT     1 year          -1
108        B   36 months           RENT    4 years          -1
111        E   60 months           RENT  10+ years          -1
118        C   36 months       MORTGAGE    8 years          -1
124        A   36 months           RENT  10+ years          -1
132        B   36 months           RENT    2 years          -1
136        B   36 months           RENT    8 years          -1
138        C   60 months           RENT  10+ years          -1
140        C   36 months       MORTGAGE     1 year          -1
151        A   36 months            OWN        n/a          -1
158        C   36 months           RENT    5 years          -1
...      ...         ...            ...        ...         ...
102646     G   60 months       MORTGAGE  10+ years           1
82309      B   36 months       MORTGAGE    6 years           1
108092     D   60 months           RENT  10+ years           1
69452      C   60 months       MORTGAGE    7 years           1
40648      C   36 months       MORTGAGE   < 1 year           1
67145      C   36 months       MORTGAGE   < 1 year           1
118733     B   36 months       MORTGAGE    3 years           1
89420      B   36 months       MORTGAGE  10+ years           1
116139     B   36 months           RENT    3 years           1
113939     C   36 months       MORTGAGE    3 years           1
70221      C   36 months           RENT    8 years           1
87729      B   36 months           RENT    4 years           1
56653      C   36 months           RENT  10+ years           1
105655     B   60 months            OWN    5 years           1
60064      E   60 months       MORTGAGE  10+ years           1
33290      A   36 months       MORTGAGE    6 years           1
68860      A   36 months           RENT    4 years           1
17080      A   36 months       MORTGAGE  10+ years           1
76316      B   36 months       MORTGAGE  10+ years           1
33736      A   36 months           RENT  10+ years           1
36480      C   36 months            OWN    9 years           1
64813      A   36 months       MORTGAGE    5 years           1
57435      B   36 months       MORTGAGE        n/a           1
89869      B   36 months       MORTGAGE  10+ years           1
107788     A   36 months           RENT    9 years           1
71408      B   36 months       MORTGAGE  10+ years           1
16016      A   36 months            OWN   < 1 year           1
44603      A   36 months       MORTGAGE  10+ years           1
114173     C   36 months       MORTGAGE        n/a           1
69228      C   36 months       MORTGAGE        n/a           1

[46300 rows x 5 columns]

Now, let's verify that the resulting percentage of safe and risky loans are each nearly 50%.

In [9]:
data_set[target].value_counts(normalize=True)

-1    0.5
 1    0.5
Name: safe_loans, dtype: float64

## Preprocessing your features

In [10]:
def dummies(data, columns=['pclass','name_title','embarked', 'sex']):
    for col in columns:
        data[col] = data[col].apply(lambda x: str(x))
        new_cols = [col + '_' + i for i in data[col].unique()]
        data = pd.concat([data, pd.get_dummies(data[col], prefix=col)[new_cols]], axis=1)
        del data[col]
    return data

In [11]:
#grade, home_ownership, target
cols = ['grade', 'term','home_ownership', 'emp_length']
data_set = dummies(data_set, columns=cols)
data_set.head()

,safe_loans,grade_C,grade_F,grade_B,grade_D,grade_A,grade_E,grade_G,term_ 60 months,term_ 36 months,...,emp_length_3 years,emp_length_10+ years,emp_length_1 year,emp_length_9 years,emp_length_2 years,emp_length_8 years,emp_length_7 years,emp_length_5 years,emp_length_n/a,emp_length_6 years
1,-1,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
6,-1,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7,-1,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
10,-1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
12,-1,0,0,1,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0

In [12]:
train_data, test_data = train_test_split(data_set, test_size=0.2, random_state=33)
trainX, trainY = train_data[train_data.columns[1:]], pd.DataFrame(train_data[target])
testX, testY = test_data[test_data.columns[1:]], pd.DataFrame(test_data[target])

#### split base on the error

In [13]:
def count_errors(labels_in_node):
    if len(labels_in_node) == 0:
        return 0
    
    positive_ones = labels_in_node.apply(lambda x: x==1).sum()
    negative_ones = labels_in_node.apply(lambda x: x==-1).sum()
    
    return min(positive_ones, negative_ones)


def best_split(data, features, target):
    # return the best feature
    best_feature = None
    best_error = 2.0 
    num_data_points = float(len(data))  

    for feature in features:
        
        # 左分支对应当前特征为0的数据点
        left_split = data[data[feature] == 0]
        
        # 右分支对应当前特征为1的数据点
        right_split = data[data[feature] == 1] 
        
        # 计算左边分支里error个数
        left_misses = count_errors(left_split[target])            

        # 计算右边分支里error个数
        right_misses = count_errors(right_split[target])
            
        # 计算当前划分之后的分类犯错率
        error = (left_misses + right_misses) * 1.0 / num_data_points

        # 更新应选特征和错误率，注意错误越低说明该特征越好
        if error < best_error:
            best_error = error
            best_feature = feature
    return best_feature

#### split base on the entropy

In [14]:
def entropy(labels_in_node):

    n = len(labels_in_node)
    s1 = (labels_in_node==1).sum()
    if s1 == 0 or s1 == n:
        return 0
    
    p1 = float(s1) / n
    p0 = 1 - p1
    return -p0 * np.log2(p0) - p1 * np.log2(p1)


def best_split_entropy(data, features, target):
    
    best_feature = None
    best_info_gain = float('-inf') 
    num_data_points = float(len(data))
    # 计算划分之前数据集的整体熵值
    entropy_original = entropy(data[target])

    for feature in features:
        
        # 左分支对应当前特征为0的数据点
        left_split = data[data[feature] == 0]
        
        # 右分支对应当前特征为1的数据点
        right_split = data[data[feature] == 1] 
        
        # 计算左边分支的熵值
        left_entropy = entropy(left_split[target])            

        # 计算右边分支的熵值
        right_entropy = entropy(right_split[target])
            
        # 计算左边分支与右分支熵值的加权和（数据集划分后的熵值）
        entropy_split = len(left_split) / num_data_points * left_entropy + len(right_split) / num_data_points * right_entropy
        
        # 计算划分前与划分后的熵值差得到信息增益
        info_gain = entropy_original - entropy_split

        # 更新最佳特征和对应的信息增益的值
        if info_gain > best_info_gain:
            best_info_gain = info_gain
            best_feature = feature
    return best_feature

construct tree node class

In [ ]:
class TreeNode:
    def __init__(self, is_leaf, prediction, split_feature):
        self.is_leaf = is_leaf
        self.prediction = prediction
        self.split_feature = split_feature
        self.left = None
        self.right = None

construct decision tree class

In [ ]:
from sklearn.base import BaseEstimator
from sklearn.metrics import accuracy_score
class MyDecisionTree(BaseEstimator):
    
    def __init__(self, max_depth, min_error):
        self.max_depth = max_depth
        self.min_error = min_error
    
    def fit(self, X, Y, data_weights = None):
        
        data_set = pd.concat([X, Y], axis=1)
        features = X.columns
        target = Y.columns[0]
        self.root_node = self.create_tree(data_set, features, 
                               target, current_depth = 0, max_depth = self.max_depth, min_error=self.min_error)
        
        
    def predict(self, X):
        prediction = X.apply(lambda row: self.predict_single_data(self.root_node, row), axis=1)
        return prediction
        
        
    def score(self, testX, testY):
        target = testY.columns[0]
        result = self.predict(testX)
        return accuracy_score(testY[target], result)
    
    
    def create_tree(self, data, features, target, current_depth = 0, max_depth = 10, min_error=0):

        remaining_features = features[:]

        target_values = data[target]

        termination 1  bonus task
        if count_errors(target_values) <= min_error:
            print("Termination 1 reached.")     
            return self.create_leaf(target_values)


        if len(remaining_features) == 0:
            print("Termination 2 reached.")    
            return self.create_leaf(target_values)    

        if current_depth >= max_depth: 
            print("Termination 3 reached.")
            return self.create_leaf(target_values)


        #split_feature = best_split(data, features, target)
        split_feature = best_split_entropy(data, features, target)  # 根据信息增益来划分

        # 选出最佳特征后，该特征为0的数据分到左边，该特征为1的数据分到右边
        left_split = data[data[split_feature] == 0]
        right_split = data[data[split_feature] == 1]

        # 剔除已经用过的特征
        remaining_features = remaining_features.drop(split_feature)
        print("Split on feature %s. (%s, %s)" % (split_feature, str(len(left_split)), str(len(right_split))))

        # 如果当前数据全部划分到了一边，直接创建叶子节点返回即可
        if len(left_split) == len(data):
            print("Perfect split!")
            return self.create_leaf(left_split[target])
        if len(right_split) == len(data):
            print("Perfect split!")
            return self.create_leaf(right_split[target])

        # 递归上面的步骤
        left_tree = self.create_tree(left_split, remaining_features, target, current_depth + 1, max_depth, min_error)        
        right_tree = self.create_tree(right_split,remaining_features,target, current_depth + 1, max_depth, min_error)


        #生成当前的树节点
        result_node = TreeNode(False, None, split_feature)
        result_node.left = left_tree
        result_node.right = right_tree
        return result_node    
    
    
    
    def create_leaf(self, target_values):

        leaf = TreeNode(True, None, None)

        num_positive_ones = len(target_values[target_values == +1])
        num_negative_ones = len(target_values[target_values == -1])

        if num_positive_ones > num_negative_ones:
            leaf.prediction = 1
        else:
            leaf.prediction = -1
    
        return leaf 
    
    
    
    def predict_single_data(self, tree, x, annotate = False):   

        if tree.is_leaf:
            if annotate: 
                print("leaf node, predicting %s" % tree.prediction)
            return tree.prediction 
        
        else:
            split_feature_value = x[tree.split_feature]

            if annotate: 
                print("Split on %s = %s" % (tree.split_feature, split_feature_value))
            if split_feature_value == 0:
                return self.predict_single_data(tree.left, x, annotate)
            else:
                return self.predict_single_data(tree.right, x, annotate)    
    
    def count_leaves(self):
        return self.count_leaves_helper(self.root_node)
    
    def count_leaves_helper(self, tree):
        if tree.is_leaf:
            return 1
        return self.count_leaves_helper(tree.left) + self.count_leaves_helper(tree.right)

In [ ]:
#my_decesion_tree = create_tree(train_data, features, target, current_depth = 0, max_depth = 10)
m = MyDecisionTree(max_depth = 10, min_error = 1e-15)

In [ ]:
m.fit(trainX, trainY)

In [ ]:
m.score(testX, testY)